import os
import sys
from pathlib import Path
import io
import pytest
import openpyxl
from unittest.mock import MagicMock, patch

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from fastapi.testclient import TestClient

import main
from backend.routers.travel_allowance import build_ta_excel_workbook

client = TestClient(main.app)


@pytest.fixture(autouse=True)
def cleanup():
    main.app.dependency_overrides.clear()
    from backend.core.cache import cache
    cache.clear()
    yield
    main.app.dependency_overrides.clear()
    cache.clear()


def test_generate_ta_multi_sheet_workbook():
    mock_district_data = {
        "district": "Jamui",
        "month": "2026-09",
        "rate_per_km": 4.0,
        "roster": [
            {
                "staff_name": "Test FO 1",
                "designation": "Field Officer",
                "total_km": 100.0,
                "gross_amount": 400.0,
                "deduction_amount": 50.0,
                "deduction_reason": "Detour",
                "final_payable_amount": 350.0,
                "status": "APPROVED",
                "days": [
                    {
                        "day": i,
                        "date": f"2026-09-{i:02d}",
                        "morning_km": 1000 + i * 10,
                        "evening_km": 1010 + i * 10,
                        "total_km": 10.0,
                        "visited_names": "Clinic A",
                        "purpose": "Followup",
                        "is_manual_override": False,
                        "admin_remarks": ""
                    }
                    for i in range(1, 11)
                ]
            },
            {
                "staff_name": "Test FO 2",
                "designation": "Field Officer",
                "total_km": 50.0,
                "gross_amount": 200.0,
                "deduction_amount": 0.0,
                "deduction_reason": "",
                "final_payable_amount": 200.0,
                "status": "SUBMITTED",
                "days": []
            }
        ]
    }

    wb_bytes = build_ta_excel_workbook(mock_district_data)
    assert isinstance(wb_bytes, bytes)
    assert len(wb_bytes) > 0

    wb = openpyxl.load_workbook(io.BytesIO(wb_bytes))
    sheetnames = wb.sheetnames
    assert "DASHBOARD" in sheetnames
    assert any("Test FO 1" in s for s in sheetnames)
    assert any("Test FO 2" in s for s in sheetnames)

    ws_dash = wb["DASHBOARD"]
    # Check that header and rows exist
    dash_text = " ".join(str(cell.value) for row in ws_dash.iter_rows() for cell in row if cell.value)
    assert "Test FO 1" in dash_text
    assert "Jamui" in dash_text or "Field Officer" in dash_text
    assert "SUM" in dash_text  # Excel =SUM(...) formulas present

    # Check staff 1 sheet
    fo1_sheet = next(s for s in sheetnames if "Test FO 1" in s)
    ws_fo1 = wb[fo1_sheet]
    fo1_text = " ".join(str(cell.value) for row in ws_fo1.iter_rows() for cell in row if cell.value)
    assert "Clinic A" in fo1_text


def test_export_excel_endpoint_and_rbac():
    # 1. Sub-Admin outside district -> 403
    with patch("backend.core.security.get_current_user", return_value={"uid": "u1", "role": "SUB_ADMIN", "allowed_districts": ["Gaya"]}):
        res = client.get("/admin/ta/export-excel?month=2026-09&district=Patna")
        assert res.status_code == 403

    # 2. Main Incharge / Admin -> 200 with Excel stream
    with patch("backend.core.security.get_current_user", return_value={"uid": "u2", "role": "MAIN_INCHARGE", "allowed_districts": ["All"]}):
        with patch("backend.routers.travel_allowance.get_district_ta_roster", return_value={
            "status": "success",
            "month": "2026-09",
            "district": "Gaya",
            "rate_per_km": 4.0,
            "roster": [
                {
                    "staff_name": "Ramesh Kumar",
                    "designation": "Field Officer",
                    "total_km": 100.0,
                    "gross_amount": 400.0,
                    "deduction_amount": 0.0,
                    "final_payable_amount": 400.0,
                    "status": "APPROVED",
                    "days": []
                }
            ]
        }):
            res = client.get("/admin/ta/export-excel?month=2026-09&district=Gaya")
            assert res.status_code == 200
            assert "application/vnd.openxmlformats" in res.headers.get("content-type", "")
            assert "TA_Gaya_2026-09.xlsx" in res.headers.get("content-disposition", "")
            assert len(res.content) > 0

            # Validate generated bytes as valid excel
            wb = openpyxl.load_workbook(io.BytesIO(res.content))
            assert "DASHBOARD" in wb.sheetnames
